require('plugins')
require('options')
require('theme-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('nvim-tree-config')
require('autopairs-config')
require('lsp-config')
require('rnvimr-config')
vim.cmd('colorscheme neodark')
